# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#sample strength exercises
Exercise.create(name: "Flat Barbell Press", description: "The primary muscles that are worked in a bench press are the triceps brachii and pectoralis major with the anterior (front) deltoids, traps & back as secondary muscles used in the flat barbell bench press.", category: "strength")
Exercise.create(name: "Dumbbell Press", description: "The Dumbbell Bench Press is basic principal exercise that can place greater absolute intensity on muscles exercised relative to auxiliary exercises. Because the Dumbbell Bench Press movement is a compound movement (An exercise that involves two or more joint movements) it is a great chest exercise for developing both mass and strength; which is why it is a favorite chest exercise by many.", category: "strength")
Exercise.create(name: "Dips", description: "The dip or push-ups is an exercise used in strength training. Narrow, shoulder-width dips primarily train the triceps, with major synergists being the anterior deltoid, the pectoralis muscles (sternal, clavicular, and minor), and the rhomboid muscles of the back (in that order).", category: "strength")
Exercise.create(name: "Push-Ups", description: "The push-up is a very common strength training exercise that is used by an array of individuals interested in improving their strength, including members of the military, bodybuilders and general fitness participants. Completing push-ups is effective at developing upper body strength. There are options that all strength levels can incorporate to make the exercise easier or more difficult.", category: "strength")
Exercise.create(name: "Pull-Ups", description: "A pull-up is an upper-body compound pulling exercise. Although it can be performed with any grip, in recent years some have used the term to refer more specifically to a pull-up performed with a palms-forward position.", category: "strength")
Exercise.create(name: "Chin-Ups", description: "The chin-up (also known as a chin or chinup) is a strength training exercise. People frequently do this exercise with the intention of strengthening muscles such as the latissimus dorsi and biceps, which extend the shoulder and flex the elbow, respectively.", category: "strength")
Exercise.create(name: "Lat Pull-Downs", description: "The pulldown exercise is a strength training exercise designed to develop the latissimus dorsi muscle. It performs the functions of downward rotation and depression of the scapulae combined with adduction and extension of the shoulder joint. The cable lat pulldown is done where the handle is moved via a cable pulley, as opposed to doing pulldowns on a leverage machine.", category: "strength")
Exercise.create(name: "Barbell Squat", description: "In strength training and fitness, the squat is a compound, full body exercise that trains primarily the muscles of the thighs, hips and buttocks, quadriceps femoris muscle (vastus lateralis, vastus medialis, vastus intermedius and rectus femoris), hamstrings, as well as strengthening the bones, ligaments and insertion of the tendons throughout the lower body.", category: "strength")
Exercise.create(name: "Leg Press", description: "The leg press is a weight training exercise in which the individual pushes a weight or resistance away from them using their legs. The term leg press also refers to the apparatus used to perform this exercise. The leg press can be used to evaluate an athlete's overall lower body strength (from knee joint to hip).", category: "strength")
Exercise.create(name: "Dumbbell Lunges", description: "A lunge can refer to any position of the human body where one leg is positioned forward with knee bent and foot flat on the ground while the other leg is positioned behind. It is used by athletes in cross-training for sports, by weight-trainers as a fitness exercise, and by yogis as part of an asana regimen.", category: "strength")
Exercise.create(name: "Standing Barbell Curls", description: "The barbell curl specifically targets the biceps brachii which is located on the front part of the arm between the shoulder and the elbow. This muscle's primary function is elbow flexion and forearm supination. The biceps also has two heads known as the long head and the short head.", category: "strength")
Exercise.create(name: "Standing Dumbbell Curls", description: "The dumbbell curl, similarly to the barbell curl, specifically targets the biceps brachii which is located on the front part of the arm between the shoulder and the elbow. This muscle's primary function is elbow flexion and forearm supination. The biceps also has two heads known as the long head and the short head.", category: "strength")
Exercise.create(name: "Seated Dumbbell Curls", description: "The dumbbell curl, similarly to the barbell curl, specifically targets the biceps brachii which is located on the front part of the arm between the shoulder and the elbow. This muscle's primary function is elbow flexion and forearm supination. The biceps also has two heads known as the long head and the short head.", category: "strength")
Exercise.create(name: "Skull Crushers", description: "Lying triceps extensions, also known as skull crushers and French extensions or French presses, are a strength exercise used in many different forms of strength training. Lying triceps extensions are one of the most stimulating exercises to the entire triceps muscle group in the upper arm.", category: "strength")
Exercise.create(name: "Cable Pressdowns", description: "A pushdown is a strength training exercise used for strengthening the triceps muscles in the back of the arm. The exercise is completed by pushing an object downward against resistance. This exercise is an example of the primary function of the triceps, extension of the elbow joint. It is a little-known fact that doing the triceps pushdown also works the biceps muscle as well.", category: "strength")

#sample cardio exercises
Exercise.create(name: "Running", description: "Running is a method of terrestrial locomotion allowing humans and other animals to move rapidly on foot. Running is a type of gait characterized by an aerial phase in which all feet are above the ground (though there are exceptions). This is in contrast to walking, where one foot is always in contact with the ground, the legs are kept mostly straight and the center of gravity vaults over the stance leg or legs in an inverted pendulum fashion.", category: "cardio")
Exercise.create(name: "Yoga", description: "Yoga is a group of physical, mental, and spiritual practices or disciplines which originated in ancient India. There is a broad variety of yoga schools, practices, and goals[2] in Hinduism, Buddhism, and Jainism. Among the most well-known types of yoga are Hatha yoga and Rāja yoga.", category: "cardio")
Exercise.create(name: "Pilates", description: "Pilates is a physical fitness system developed in the early 20th century by Joseph Pilates, after whom it was named. Pilates called his method 'Contrology'.", category: "cardio")
Exercise.create(name: "Swimming", description: "Swimming is the self-propulsion of a person through fresh or salt water, usually for recreation, sport, exercise, or survival. Locomotion is achieved through coordinated movement of the limbs, the body, or both.", category: "cardio")
Exercise.create(name: "Biking", description: "Cycling, also called bicycling or biking, is the use of bicycles for transport, recreation, exercise or sport. People engaged in cycling are referred to as 'cyclists', 'bikers', or less commonly, as 'bicyclists'. Apart from two-wheeled bicycles, 'cycling' also includes the riding of unicycles, tricycles, quadracycles, recumbent and similar human-powered vehicles (HPVs).", category: "cardio")
Exercise.create(name: "Stationary Bike", description: "A stationary bicycle (also known as exercise bicycle, exercise bike, spinning bike, spin bike, or exercycle) is a device with saddle, pedals, and some form of handlebars arranged as on a bicycle, but used as exercise equipment rather than transportation", category: "cardio")
Exercise.create(name: "Jump Roping", description: "A skipping rope (British English) or jump rope (American English) is a tool used in the sport of jump rope where one or more participants jump over a rope swung so that it passes under their feet and over their heads.", category: "cardio")
Exercise.create(name: "Wii Tennis", description: "Try to tell me this isn't exercise.", category: "cardio")

#sample users
curr_password = "password1"
User.create(first_name:"Rani", last_name:"Shah", age:25, height:"5'4", weight:150, username:"ranishah", email:"ranishah@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/33222490")
User.create(first_name:"Adam", last_name:"Towers", age:25, height:"5'4", weight:150, username:"adamtowers", email:"adamtowers@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/28485815")
User.create(first_name:"Manuel", last_name:"Grullon", age:25, height:"5'4", weight:150, username:"manuelgrullon", email:"manuelgrullon@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/27866970")
User.create(first_name:"Patricia", last_name:"Wong", age:25, height:"5'4", weight:150, username:"patriciawong", email:"patriciawong@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/13529142_10157070972765693_308998561448850814_n.jpg?_nc_cat=0&oh=bf3284575f5345dafb57ae0cae0d819c&oe=5B5C924B")
User.create(first_name:"Helen", last_name:"Liutongco", age:25, height:"5'4", weight:150, username:"helenliutongco", email:"helenliutongco@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/32890150")
User.create(first_name:"Greg", last_name:"Dwyer", age:25, height:"5'4", weight:150, username:"gregdwyer", email:"gregdwyer@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/26555832")
User.create(first_name:"Eric", last_name:"Kim", age:25, height:"5'4", weight:150, username:"erickim", email:"erickim@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"http://www.free-icons-download.net/images/user-male-icon-61342.png")
User.create(first_name:"Henry", last_name:"Zhang", age:25, height:"5'4", weight:150, username:"henryzhang", email:"henryzhang@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/25620736")
User.create(first_name:"Jeremy", last_name:"Gottfried", age:25, height:"5'4", weight:150, username:"jeremygottfried", email:"jeremygottfried@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/34523280")
User.create(first_name:"Jon", last_name:"Valdesuso", age:25, height:"5'4", weight:150, username:"jonvaldesuso", email:"jonvaldesuso@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/31379344")
User.create(first_name:"Justin", last_name:"Dumadag", age:25, height:"5'4", weight:150, username:"justindumadag", email:"justindumadag@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/32379988")
User.create(first_name:"Kate", last_name:"Schlunz", age:25, height:"5'4", weight:150, username:"kateschlunz", email:"kateschlunz@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/23439408")
User.create(first_name:"Vicky", last_name:"Huang", age:25, height:"5'4", weight:150, username:"vickyhuang", email:"vickyhuang@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/33406642")
User.create(first_name:"Laura", last_name:"Campbell", age:25, height:"5'4", weight:150, username:"lauracampbell", email:"lauracampbell@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/35786146")
User.create(first_name:"Dick", last_name:"Ward", age:25, height:"5'4", weight:150, username:"dickward", email:"dickward@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/30528377")
User.create(first_name:"Frank", last_name:"McManus", age:25, height:"5'4", weight:150, username:"frankmcmanus", email:"frankmcmanus@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/33381723")
User.create(first_name:"Garry", last_name:"Clerge", age:25, height:"5'4", weight:150, username:"garryclerge", email:"garryclerge@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/31334252")
User.create(first_name:"Joe", last_name:"Moloughney", age:25, height:"5'4", weight:150, username:"joemoloughney", email:"joemoloughney@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"http://www.free-icons-download.net/images/user-male-icon-61342.png")
User.create(first_name:"Mike", last_name:"McNeeley", age:25, height:"5'4", weight:150, username:"mikemcneeley", email:"mikemcneeley@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/753223")
User.create(first_name:"Rishi", last_name:"Tirumala", age:25, height:"5'4", weight:150, username:"rishitirumala", email:"rishitirumala@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/552786")
User.create(first_name:"Alice", last_name:"Lin", age:25, height:"5'4", weight:150, username:"alicelin", email:"alicelin@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVGHMPlxc1lAsiVyelyVF4WWzGup61CNK_odzwlL09R6S583K--w")
User.create(first_name:"Arthur", last_name:"Lurye", age:25, height:"5'4", weight:150, username:"arthurlurye", email:"arthurlurye@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/5193425")
User.create(first_name:"Christian", last_name:"Kim", age:25, height:"5'4", weight:150, username:"christiankim", email:"christiankim@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/34519887")
User.create(first_name:"JD", last_name:"Bean", age:25, height:"5'4", weight:150, username:"jdbean", email:"jdbean@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/11352630")
User.create(first_name:"Celeste", last_name:"Gerard", age:25, height:"5'4", weight:150, username:"celestegerard", email:"celestegerard@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"https://avatars.githubusercontent.com/u/32781613")
User.create(first_name:"Harim", last_name:"Choi", age:25, height:"5'4", weight:150, username:"harimchoi", email:"harimchoi@gmail.com", password: curr_password, password_confirmation: curr_password, picture:"http://www.free-icons-download.net/images/user-male-icon-61342.png")

#sample workouts
User.all.each do |user|
  da_workout = Workout.create(name: "sample workout #{rand(1..10)}", user: user)
  rand(2..10).times do
    da_workout.exercises << Exercise.all.sample
  end
end
